# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

# Reading the dataset

In [2]:
df=pd.read_csv(r'C:\Users\shine\Downloads\mushrooms.csv')
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

# Examining the dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [4]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [5]:
#Insights
 There is only a single unique value in the column 'veil-type'.So we can drop that column.

IndentationError: unexpected indent (<ipython-input-5-a0a4f3de500a>, line 2)

# Checking for null values

In [ ]:
df.isnull().sum()

In [ ]:
#Insights
-There are no null values in the dataset.

In [ ]:
#display the number of values of each class
df['class'].value_counts()

In [6]:
#Dropping the 'veil-type'column
df=df.drop(["veil-type"],axis=1)
df

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-above-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        s   
8123            c         b          y  ...                        s   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-color ring-number ring-type spore-print-color population habitat  
0             w           o         p                 k          s       u  
1             w           o         p                 n          n       g  
2             w           o         p                 n          n       m  
3             w           o         p                 k          s       u  
4             w           o         e                 n          a       g  
...         ...         ...       ...               ...        ...     ...  
8119          o           o         p                 b          c       l  
8120          n           o         p                 b          v       l  
8121          o           o         p                 b          c       l  
8122          w           o         e                 w          v       l  
8123          o           o         p                 o          c       l  

[8124 rows x 22 columns]

# Label Encoding


In [7]:
#Changing the datatype in to category
df=df.astype('category')
df.dtypes

class                       category
cap-shape                   category
cap-surface                 category
cap-color                   category
bruises                     category
odor                        category
gill-attachment             category
gill-spacing                category
gill-size                   category
gill-color                  category
stalk-shape                 category
stalk-root                  category
stalk-surface-above-ring    category
stalk-surface-below-ring    category
stalk-color-above-ring      category
stalk-color-below-ring      category
veil-color                  category
ring-number                 category
ring-type                   category
spore-print-color           category
population                  category
habitat                     category
dtype: object

In [8]:
#Using label encoder
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
for column in df.columns:
    df[column]=lb.fit_transform(df[column])
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-above-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-surface-below-ring  stalk-color-above-ring  stalk-color-below-ring  \
0                         2                       7                       7   
1                         2                       7                       7   
2                         2                       7                       7   
3                         2                       7                       7   
4                         2                       7                       7   

   veil-color  ring-number  ring-type  spore-print-color  population  habitat  
0           2            1          4                  2           3        5  
1           2            1          4                  3           2        1  
2           2            1          4                  3           2        3  
3           2            1          4                  2           3        5  
4           2            1          0                  3           0        1  

[5 rows x 22 columns]

In [9]:
train_x = df.drop(["class"], axis=1).values
train_y=df['class']
test_x= df.drop(["class"], axis=1).values
test_y =df['class']


In [10]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(train_x,train_y,test_size=0.3,random_state=2)

# Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression

## lr = LogisticRegression(solver="lbfgs")
lr = LogisticRegression(solver="liblinear")
lr.fit(train_x,train_y)

print("Test Accuracy: {}%".format(round(lr.score(test_x,test_y)*100,2)))



Test Accuracy: 95.16%


In [19]:
y_pred = lr.predict(test_x)

y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [22]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   2 1138]]


# KNN

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
model=KNeighborsClassifier(n_neighbors=3)
model.fit(train_x,train_y)
prediction=model.predict(test_x)
print('The accuracy of the KNN  is',metrics.accuracy_score(prediction,test_y))


The accuracy of the KNN  is 0.9991796554552912


In [21]:
y_pred = model.predict(test_x)

y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [23]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   2 1138]]


# Random Forest

In [26]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(train_x,train_y)
y_pred=rf.predict(test_x)
print('The accouracy of Random forets classifier is',metrics.accuracy_score(y_pred,test_y))

The accouracy of Random forets classifier is 1.0


In [27]:


y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [28]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   0 1140]]


# SVM

In [29]:
from sklearn.svm import SVC

svm = SVC(random_state=42, gamma="auto")
svm.fit(train_x,train_y)
y_pred=rf.predict(test_x)
print('The accouracy of SVM is',metrics.accuracy_score(y_pred,test_y))



The accouracy of SVM is 1.0


In [30]:


y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [31]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   0 1140]]


# Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(train_x,train_y)
y_pred=rf.predict(test_x)
print('The accouracy of Naive_Bayes is',metrics.accuracy_score(y_pred,test_y))




The accouracy of Naive_Bayes is 1.0


In [33]:
y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [34]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   0 1140]]


# Decision Tree

In [35]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(train_x,train_y)
y_pred=rf.predict(test_x)
print('The accouracy of decision tree is',metrics.accuracy_score(y_pred,test_y))


The accouracy of decision tree is 1.0


In [36]:

y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [37]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(test_y, y_pred)

print(cf_matrix)

[[1298    0]
 [   0 1140]]


# Conclusion

From the confusion metrics we see that our train and test data are balanced and
most of the classification methods show 100% accuracy